#!/bin/bash
# shellcheck disable=SC1091  # Sourced files are resolved at runtime
set -euo pipefail

# ─── Interactive setup wizard for claude-pal-action ──────────
# Alternative to the /setup Claude Code skill for users without Claude Code.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Source config var parser for tracking known config variables
if [ -f "$SCRIPT_DIR/lib/config-vars.sh" ]; then
    # shellcheck source=lib/config-vars.sh
    source "$SCRIPT_DIR/lib/config-vars.sh"
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

echo ""
echo -e "${BOLD}Claude Agent Dispatch — Setup Wizard${NC}"
echo "═══════════════════════════════════════"
echo ""

# ── Step 0: Check prerequisites ──────────────────────────────────
echo -e "${CYAN}Checking prerequisites...${NC}"
bash "$SCRIPT_DIR/check-prereqs.sh" || {
    echo -e "${RED}Prerequisites check failed. Please install missing tools and re-run.${NC}"
    exit 1
}
echo ""

# ── Step 1: Choose setup mode ───────────────────────────────────
echo -e "${BOLD}Step 1: Setup Mode${NC}"
echo ""
echo "How would you like to set up the agent dispatch system?"
echo ""
echo "  [1] Standalone mode (recommended)"
echo "      All scripts, prompts, and workflows are copied into your repo."
echo "      You own everything and can modify freely."
echo "      Per-repo config isolation out of the box."
echo ""
echo "  [2] Reference mode"
echo "      Workflows in your repo call back to this upstream repo."
echo "      Scripts run from a clone on your runner."
echo "      You get updates automatically via version tags."
echo ""

read -rp "Choose mode [1/2]: " SETUP_MODE
SETUP_MODE="${SETUP_MODE:-1}"

if [[ "$SETUP_MODE" != "1" && "$SETUP_MODE" != "2" ]]; then
    echo -e "${RED}Invalid choice. Please enter 1 or 2.${NC}"
    exit 1
fi

# Map user-facing numbering to internal: 1=standalone(internal 2), 2=reference(internal 1)
if [[ "$SETUP_MODE" == "1" ]]; then
    SETUP_MODE="2"
elif [[ "$SETUP_MODE" == "2" ]]; then
    SETUP_MODE="1"
fi

echo ""

# ── Step 2: Gather project info ──────────────────────────────────
echo -e "${BOLD}Step 2: Project Information${NC}"
echo ""

read -rp "Target repository (owner/repo): " TARGET_REPO
if [ -z "$TARGET_REPO" ]; then
    echo -e "${RED}Repository is required.${NC}"
    exit 1
fi

read -rp "Bot account username: " BOT_USER
if [ -z "$BOT_USER" ]; then
    echo -e "${RED}Bot username is required.${NC}"
    exit 1
fi

read -rp "Default branch [main]: " DEFAULT_BRANCH
DEFAULT_BRANCH="${DEFAULT_BRANCH:-main}"

read -rp "Test command (leave empty to skip pre-PR test gate): " TEST_COMMAND

read -rp "Extra tools for the agent (e.g., Bash(npm:*),Bash(cargo:*)) [none]: " EXTRA_TOOLS

if [ "$SETUP_MODE" = "2" ]; then
    echo ""
    read -rp "Path to your local clone of $TARGET_REPO: " TARGET_REPO_PATH
    if [ -z "$TARGET_REPO_PATH" ] || [ ! -d "$TARGET_REPO_PATH" ]; then
        echo -e "${RED}Valid path to local repo clone is required for standalone mode.${NC}"
        exit 1
    fi
fi

echo ""

# ── Step 3: Generate config ─────────────────────────────────────
echo -e "${BOLD}Step 3: Generating configuration${NC}"

if [ "$SETUP_MODE" = "1" ]; then
    CONFIG_FILE="$REPO_ROOT/config.env"
else
    CONFIG_DIR="$TARGET_REPO_PATH/.agent-dispatch"
    mkdir -p "$CONFIG_DIR"
    CONFIG_FILE="$CONFIG_DIR/config.env"
fi

cat > "$CONFIG_FILE" << EOF
# Claude Agent Dispatch — Configuration for $TARGET_REPO
# Generated by setup.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')

AGENT_BOT_USER="$BOT_USER"
EOF

if [ -n "$TEST_COMMAND" ]; then
    echo "AGENT_TEST_COMMAND=\"$TEST_COMMAND\"" >> "$CONFIG_FILE"
fi

if [ -n "$EXTRA_TOOLS" ]; then
    echo "AGENT_EXTRA_TOOLS=\"$EXTRA_TOOLS\"" >> "$CONFIG_FILE"
fi

echo -e "  ${GREEN}✓${NC} config.env written to $CONFIG_FILE"

# ── Step 3b (standalone): Copy scripts, lib, and prompts ─────────
if [ "$SETUP_MODE" = "2" ]; then
    AGENT_DIR="$TARGET_REPO_PATH/.agent-dispatch"

    echo "  Copying scripts..."
    mkdir -p "$AGENT_DIR/scripts/lib"
    cp "$REPO_ROOT/scripts/agent-dispatch.sh" "$AGENT_DIR/scripts/"
    cp "$REPO_ROOT/scripts/cleanup.sh" "$AGENT_DIR/scripts/"
    cp "$REPO_ROOT/scripts/check-prereqs.sh" "$AGENT_DIR/scripts/"
    cp "$REPO_ROOT/scripts/create-labels.sh" "$AGENT_DIR/scripts/"
    cp "$REPO_ROOT/scripts/lib/"*.sh "$AGENT_DIR/scripts/lib/"
    chmod +x "$AGENT_DIR/scripts/"*.sh
    echo -e "  ${GREEN}✓${NC} Scripts copied to $AGENT_DIR/scripts/"

    echo "  Copying prompts..."
    mkdir -p "$AGENT_DIR/prompts"
    cp "$REPO_ROOT/prompts/"*.md "$AGENT_DIR/prompts/"
    echo -e "  ${GREEN}✓${NC} Prompts copied to $AGENT_DIR/prompts/"

    echo "  Copying labels.txt..."
    cp "$REPO_ROOT/labels.txt" "$AGENT_DIR/"
    echo -e "  ${GREEN}✓${NC} labels.txt copied"

    # Write upstream tracking file for /update support
    echo "  Writing version tracking..."
    CURRENT_SHA=$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo "unknown")
    {
        echo "# Upstream tracking for standalone agent-dispatch installation"
        echo "# Do not edit manually — managed by /update skill and setup.sh"
        echo "repo: https://github.com/jnurre64/claude-pal-action.git"
        echo "version: $CURRENT_SHA"
        echo "synced_at: \"$(date -u '+%Y-%m-%dT%H:%M:%SZ')\""
        echo "checksums:"
        # Dynamically find all copied files for checksum tracking
        while IFS= read -r -d '' tracked_path; do
            tracked_file="${tracked_path#"$AGENT_DIR/"}"
            file_checksum=$(sha256sum "$tracked_path" | cut -d' ' -f1)
            echo "  ${tracked_file}: \"sha256:${file_checksum}\""
        done < <(find "$AGENT_DIR/scripts" "$AGENT_DIR/prompts" -type f -print0 2>/dev/null)
        if [ -f "$AGENT_DIR/labels.txt" ]; then
            file_checksum=$(sha256sum "$AGENT_DIR/labels.txt" | cut -d' ' -f1)
            echo "  labels.txt: \"sha256:${file_checksum}\""
        fi
        # Track known config vars for future new-var detection
        if type parse_config_vars &>/dev/null && [ -f "$REPO_ROOT/config.defaults.env.example" ]; then
            echo "config_vars:"
            parse_config_vars "$REPO_ROOT/config.defaults.env.example" | while read -r var; do
                echo "  - $var"
            done
        fi
    } > "$AGENT_DIR/.upstream"
    echo -e "  ${GREEN}✓${NC} Version tracking written (.upstream)"
fi

echo ""

# ── Step 4: Create labels ────────────────────────────────────────
echo -e "${BOLD}Step 4: Creating labels on $TARGET_REPO${NC}"
read -rp "Create agent labels now? [Y/n]: " CREATE_LABELS
CREATE_LABELS="${CREATE_LABELS:-Y}"

if [[ "$CREATE_LABELS" =~ ^[Yy] ]]; then
    bash "$SCRIPT_DIR/create-labels.sh" "$TARGET_REPO"
else
    echo -e "  ${YELLOW}!${NC} Skipped. Run later: ./scripts/create-labels.sh $TARGET_REPO"
fi
echo ""

# ── Step 5: Generate workflows ───────────────────────────────────
echo -e "${BOLD}Step 5: Generating workflow files${NC}"

if [ "$SETUP_MODE" = "2" ]; then
    WORKFLOWS_DIR="$TARGET_REPO_PATH/.github/workflows"
    TEMPLATES_DIR="$REPO_ROOT/.claude/skills/setup/templates/standalone"
else
    TEMPLATES_DIR="$REPO_ROOT/.claude/skills/setup/templates"
    read -rp "Path to target repo's .github/workflows/ directory: " WORKFLOWS_DIR
    if [ -z "$WORKFLOWS_DIR" ]; then
        WORKFLOWS_DIR="$REPO_ROOT/generated-workflows"
        echo -e "  ${YELLOW}!${NC} No path provided. Writing to $WORKFLOWS_DIR"
    fi
fi
mkdir -p "$WORKFLOWS_DIR"

# Check for existing workflow files that would be overwritten
CONFLICTS=()
for template in "$TEMPLATES_DIR"/*.yml; do
    filename=$(basename "$template")
    output_name="${filename/caller-/agent-}"
    if [ -f "$WORKFLOWS_DIR/$output_name" ]; then
        CONFLICTS+=("$output_name")
    fi
done

WORKFLOW_PREFIX="agent"

if [ ${#CONFLICTS[@]} -gt 0 ]; then
    echo -e "  ${YELLOW}!${NC} These workflow files already exist:"
    for f in "${CONFLICTS[@]}"; do
        echo "      - $f"
    done
    echo ""
    echo "  Options:"
    echo "    [1] Overwrite existing files"
    echo "    [2] Use a different prefix (e.g., 'claude-agent' instead of 'agent')"
    echo "    [3] Skip workflow generation"
    echo ""
    read -rp "  Choose [1/2/3]: " CONFLICT_CHOICE
    CONFLICT_CHOICE="${CONFLICT_CHOICE:-3}"

    case "$CONFLICT_CHOICE" in
        1) ;; # proceed with default prefix
        2)
            read -rp "  Enter prefix (e.g., 'claude-agent'): " WORKFLOW_PREFIX
            if [ -z "$WORKFLOW_PREFIX" ]; then
                WORKFLOW_PREFIX="agent"
                echo -e "  ${YELLOW}!${NC} Empty prefix, using default: agent"
            fi
            ;;
        *)
            echo -e "  ${YELLOW}!${NC} Skipped workflow generation."
            WORKFLOWS_DIR=""
            ;;
    esac
fi

if [ -n "$WORKFLOWS_DIR" ]; then
    for template in "$TEMPLATES_DIR"/*.yml; do
        filename=$(basename "$template")
        # Replace the template prefix with the chosen prefix
        # caller-triage.yml → <prefix>-triage.yml  (reference mode)
        # agent-triage.yml → <prefix>-triage.yml   (standalone mode)
        base_name="${filename#caller-}"
        base_name="${base_name#agent-}"
        output_name="${WORKFLOW_PREFIX}-${base_name}"
        sed "s/{{BOT_USER}}/$BOT_USER/g" "$template" > "$WORKFLOWS_DIR/$output_name"
        echo -e "  ${GREEN}✓${NC} $output_name"
    done
fi

echo ""

# ── Step 6: Secret setup guidance ────────────────────────────────
echo -e "${BOLD}Step 6: GitHub Secrets${NC}"
echo ""
echo "Your target repo needs these secrets:"
echo "  - AGENT_PAT        — Fine-grained PAT for the bot account (required)"
echo "  - AGENT_GIST_PAT   — Classic PAT with gist scope (optional, for cleanup)"
echo ""
read -rp "Set AGENT_PAT now via gh CLI? [Y/n]: " SET_PAT
SET_PAT="${SET_PAT:-Y}"

if [[ "$SET_PAT" =~ ^[Yy] ]]; then
    echo "Paste the bot's PAT when prompted (input is hidden):"
    gh secret set AGENT_PAT --repo "$TARGET_REPO" || echo -e "  ${YELLOW}!${NC} Failed. Set manually in repo Settings → Secrets."
else
    echo -e "  ${YELLOW}!${NC} Set later: gh secret set AGENT_PAT --repo $TARGET_REPO"
fi
echo ""

# ── Summary ──────────────────────────────────────────────────────
echo -e "${BOLD}Setup Complete${NC}"
echo "═══════════════════════════════════════"
echo ""

if [ "$SETUP_MODE" = "1" ]; then
    echo "Mode: Reference (workflows call upstream repo)"
    echo ""
    echo "Created:"
    echo -e "  ${GREEN}✓${NC} config.env at $CONFIG_FILE"
    echo -e "  ${GREEN}✓${NC} Caller workflows in $WORKFLOWS_DIR"
else
    echo "Mode: Standalone (all files copied into your repo)"
    echo ""
    echo "Created in $TARGET_REPO_PATH:"
    echo -e "  ${GREEN}✓${NC} .agent-dispatch/scripts/    — dispatch and utility scripts"
    echo -e "  ${GREEN}✓${NC} .agent-dispatch/prompts/    — default agent prompts"
    echo -e "  ${GREEN}✓${NC} .agent-dispatch/config.env  — project configuration"
    echo -e "  ${GREEN}✓${NC} .github/workflows/          — workflow files"
fi

echo ""
echo -e "${BOLD}Next Steps: Self-Hosted Runner${NC}"
echo "───────────────────────────────────────"
echo ""

# Determine the owner type for the registration URL
REPO_OWNER="${TARGET_REPO%%/*}"

echo "  1. Get a registration token from the GitHub UI:"
echo ""
echo -e "     ${CYAN}https://github.com/${TARGET_REPO}/settings/actions/runners/new${NC}"
echo ""
echo "     (If this is an org repo, you can register at the org level instead:"
echo "      https://github.com/organizations/${REPO_OWNER}/settings/actions/runners/new)"
echo ""
echo "  2. Create a runner directory and follow the download steps shown in the UI:"
echo ""
echo -e "     ${CYAN}mkdir -p ~/actions-runner-$(basename "$TARGET_REPO") && cd ~/actions-runner-$(basename "$TARGET_REPO")${NC}"
echo ""
echo "  3. Register the runner with the required labels:"
echo ""
echo -e "     ${CYAN}./config.sh --url https://github.com/${REPO_OWNER} --token <TOKEN> \\${NC}"
echo -e "     ${CYAN}  --name <runner-name> --labels self-hosted,agent --work _work${NC}"
echo ""
echo "  4. Add ANTHROPIC_API_KEY to the runner's .env file (systemd does not"
echo "     source ~/.bashrc — the .env file is required):"
echo ""
echo -e "     ${CYAN}echo 'ANTHROPIC_API_KEY=sk-ant-...' >> .env${NC}"
echo -e "     ${CYAN}chmod 600 .env${NC}"
echo ""
echo "     For individual solo-developer use, CLAUDE_CODE_OAUTH_TOKEN is also"
echo "     supported instead of ANTHROPIC_API_KEY — see docs/authentication.md"
echo "     for guidance, Terms of Service boundaries, and setup steps."
echo ""
echo "  5. Ensure Claude Code is in PATH for systemd (if using nvm):"
echo ""
echo -e "     ${CYAN}echo \"PATH=\$HOME/.nvm/versions/node/\$(node -v)/bin:\$PATH\" >> .env${NC}"
echo ""
echo "  6. Install and start the systemd service:"
echo ""
echo -e "     ${CYAN}sudo ./svc.sh install \$(whoami)${NC}"
echo -e "     ${CYAN}sudo ./svc.sh start${NC}"
echo ""

if [ "$SETUP_MODE" = "1" ]; then
    echo "  7. Clone the upstream repo on the runner and copy config:"
    echo ""
    echo -e "     ${CYAN}git clone https://github.com/jnurre64/claude-pal-action.git ~/agent-infra${NC}"
    echo -e "     ${CYAN}cp $CONFIG_FILE ~/agent-infra/config.env${NC}"
    echo ""
    echo "  8. Commit and push the workflow files to $TARGET_REPO"
    echo ""
    echo "  9. Test: create an issue on $TARGET_REPO, add the 'agent' label"
else
    echo "  7. Commit and push all files to $TARGET_REPO"
    echo ""
    echo "  8. Test: create an issue on $TARGET_REPO, add the 'agent' label"
    echo ""
    echo "You own all the files — modify scripts, prompts, and workflows as needed."
    echo "There is no upstream dependency."
fi

echo ""
echo -e "For full runner documentation, see: ${CYAN}docs/runners.md${NC}"
echo ""
